# Generated by Django 3.1.14 on 2022-08-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_pokemon_evolution_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolution_from',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokemon_entities.pokemon'),
        ),
    ]
