# Generated by Django 3.1.14 on 2022-09-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20220822_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='pokemon_elements', to='pokemon_entities.PokemonElementType', verbose_name='Стихия'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to='pokemon_entities.pokemon', verbose_name='Покемон'),
        ),
    ]
