# Generated by Django 3.1.14 on 2022-09-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20220910_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='element_type',
            new_name='element_types',
        ),
    ]
