# Generated by Django 3.1.14 on 2022-09-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, related_name='strong_against_elements', to='pokemon_entities.PokemonElementType', verbose_name='Силён против'),
        ),
    ]
