# Generated by Django 3.1.14 on 2022-09-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20220912_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='text_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='text_jp',
            new_name='name_jp',
        ),
    ]
